------------------------------------------------------------------------
local function safe(g)
	return game.ReplicatedStorage:FindFirstChild(g) or nil
end

gloveHits = {
	["All"] = safe("GeneralHit"),
	------------------------------------------------
	["Default"] = safe("b"),
	["Extended"] = safe("b"),
	------------------------------------------------
	["ZZZZZZZ"] = safe("ZZZZZZZHit"),
	["Brick"] = safe("BrickHit"),
	["Snow"] = safe("SnowHit"),
	["Pull"] = safe("PullHit"),
	["Flash"] = safe("FlashHit"),
	["Spring"] = safe("springhit"),
	["Swapper"] = safe("HitSwapper"),
	["Bull"] = safe("BullHit"),
	["Dice"] = safe("DiceHit"),
	["Ghost"] = safe("GhostHit"),
	["Stun"] = safe("HtStun"),
	["Za Hando"] = safe("zhramt"),
	["Fort"] = safe("Fort"),
	["Magnet"] = safe("MagnetHIT"),
	["Pusher"] = safe("PusherHit"),
	["Anchor"] = safe("hitAnchor"),
	["Space"] = safe("HtSpace"),
	["Boomerang"] = safe("BoomerangH"),
	["Speedrun"] = safe("Speedrunhit"),
	["Mail"] = safe("MailHit"),
	["Golden"] = safe("GoldenHit"),
	["MR"] = safe("MisterHit"),
	["Reaper"] = safe("ReaperHit"),
	["Replica"] = safe("ReplicaHit"),
	["Defense"] = safe("DefenseHit"),
	["Killstreak"] = safe("KSHit"),
	["Reverse"] = safe("ReverseHit"),
	["Shukuchi"] = safe("ShukuchiHit"),
	["Duelist"] = safe("DuelistHit"),
	["woah"] = safe("woahHit"),
	["Ice"] = safe("IceHit"),
	["Adios"] = safe("hitAdios"),
	["Blocked"] = safe("BlockedHit"),
	["Engineer"] = safe("engiehit"),
	["Rocky"] = safe("RockyHit"),
	["Conveyor"] = safe("ConvHit"),
	["STOP"] = safe("STOP"),
	["Phantom"] = safe("PhantomHit"),
	["Wormhole"] = safe("WormHit"),
	["Acrobat"] = safe("AcHit"),
	["Plague"] = safe("PlagueHit"),
	["[REDACTED]"] = safe("ReHit"),
	["bus"] = safe("hitbus"),
	["Phase"] = safe("PhaseH"),
	["Warp"] = safe("WarpHt"),
	["Bomb"] = safe("BombHit"),
	["Bubble"] = safe("BubbleHit"),
	["Jet"] = safe("JetHit"),
	["Shard"] = safe("ShardHIT"),
	["potato"] = safe("potatohit"),
	["CULT"] = safe("CULTHit"),
	["bob"] = safe("bobhit"),
	["Buddies"] = safe("buddiesHIT"),
	["Spy"] = safe("SpyHit"),
	["Detonator"] = safe("DetonatorHit"),
	["Rage"] = safe("GRRRR"),
	["Trap"] = safe("traphi"),
	["Orbit"] = safe("Orbihit"),
	["Hybrid"] = safe("HybridCLAP"),
	["Slapple"] = safe("SlappleHit"),
	["Disarm"] = safe("DisarmH"),
	["Dominance"] = safe("DominanceHit"),
	["Link"] = safe("LinkHit"),
	["Rojo"] = safe("RojoHit"),
	["rob"] = safe("robhit"),
	["Rhythm"] = safe("rhythmhit"),
	["Nightmare"] = safe("nightmarehit"),
	["Hitman"] = safe("HitmanHit"),
	["Thor"] = safe("ThorHit"),
	["Retro"] = safe("RetroHit"),
	["Cloud"] = safe("CloudHit"),
	["Null"] = safe("NullHit"),
	["spin"] = safe("spinhit"),
	["Pylon"] = safe("PylonHit"),
	["Leafblower"] = safe("LeafblowerHit"),
	------------------------------------------------
	["Poltergeist"] = safe("UTGHit"),
	["Clock"] = safe("GeneralHit"),
	["Đồng hồ"] = safe("GeneralHit"),
	["Untitled Tag Glove"] = safe("UTGHit"),
	------------------------------------------------
	["Kinetic"] = safe("HtStun"),
	["Recall"] = safe("HtStun"),
	["Balloony"] = safe("HtStun"),
	["Sparky"] = safe("HtStun"),
	["Boogie"] = safe("HtStun"),
	["Stun"] = safe("HtStun"),
	["Coil"] = safe("HtStun"),
	------------------------------------------------
	["Diamond"] = safe("DiamondHit"),
	["Megarock"] = safe("DiamondHit"),
	------------------------------------------------
	["Moon"] = safe("CelestialHit"),
	["Jupiter"] = safe("CelestialHit"),
	------------------------------------------------
	["Mitten"] = safe("MittenHit"),
	["Hallow Jack"] = safe("HallowHIT"),
	------------------------------------------------
	["OVERKILL"] = safe("Overkillhit"),
	["The Flex"] = safe("FlexHit"),
	["Custom"] = safe("CustomHit"),
	["God's Hand"] = safe("Godshand"),
	["Error"] = safe("Errorhit"),
}
